global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"] # Requires redis exporter

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"] # Requires postgres exporter

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
