import {
  IconDashboard,
  IconUserScreen,
  IconFolder,
  IconHelp,
  IconSearch,
  IconSettings,
  IconUsers,
  IconHeartCog,
  IconCheckupList,
  IconCalendarWeekFilled,
  IconChalkboardTeacher,
  IconMessage2Code,
  IconUsersGroup,
  IconDatabase,
} from "@tabler/icons-react";

// Define NavConfig type if not imported from elsewhere
export type NavConfig = {
  main: Array<{ title: string; icon: React.FC }>;
  reports: Array<{ title: string; icon: React.FC }>;
  system: Array<{ title: string; icon: React.FC }>;
  secondary: Array<{ title: string; url: string; icon: React.FC }>;
};

export type ImagesConfig = {
  courseImages: {
    name: string;
    src: string;
  }[];
  userGroupImages: {
    name: string;
    src: string;
  }[];
  projectImages: {
    name: string;
    src: string;
    tags: string;
  }[];
};

export const data = {
  nav: {
    main: [
      {
        title: "Dashboard",
        icon: IconDashboard,
      },
      {
        title: "Users",
        icon: IconUsers,
      },
      {
        title: "User Groups",
        icon: IconUsersGroup,
      },
      {
        title: "Course",
        icon: IconChalkboardTeacher,
      },
      {
        title: "Classroom",
        icon: IconUserScreen,
      },
      {
        title: "Projects",
        icon: IconFolder,
      },
    ],
    /*   documents: [
      {
        name: "Data Library",
        url: "#",
        icon: IconDatabase,
      },
      {
        name: "Reports",
        url: "#",
        icon: IconReport,
      },
      {
        name: "Word Assistant",
        url: "#",
        icon: IconFileWord,
      },
    ], */
    reports: [
      {
        title: "Completions",
        icon: IconCheckupList,
      },
      {
        title: "Calendar",
        icon: IconCalendarWeekFilled,
      },
    ],
    system: [
      {
        title: "Data Library",
        icon: IconDatabase,
      },
      {
        title: "System Health",
        icon: IconHeartCog,
      },
      {
        title: "System Logs",
        icon: IconMessage2Code,
      },
    ],
    secondary: [
      {
        title: "Settings",
        url: "#",
        icon: IconSettings,
      },
      {
        title: "Get Help",
        url: "#",
        icon: IconHelp,
      },
      {
        title: "Search",
        url: "#",
        icon: IconSearch,
      },
    ],
  } satisfies NavConfig,

  navItemsByRole: {
    administrator: [
      "Dashboard",
      "Users",
      "User Groups",
      "Course",
      "Classroom",
      "Projects",
      "Completions",
      "Calendar",
      "Data Library",
      "System Health",
      "System Logs",
    ],
    instructor: [
      "Dashboard",
      "Users",
      "User Groups",
      "Course",
      "Classroom",
      "Projects",
      "Completions",
      "Calender",
    ],
    student: ["Classroom", "Projects", "Completions", "Calendar"],
  },

  images: {
    courseImages: [
      {
        name: "alpine-forest",
        src: "src/client/assets/courses/9f9c813d-d96a-46dc-bd19-6f7b658d218e.jpg",
      },
      {
        name: "azure-sky",
        src: "src/client/assets/courses/b146bd30-776a-4052-afab-24103530d50b.jpg",
      },
      {
        name: "crimson-sunset",
        src: "src/client/assets/courses/b899dcd9-9d1b-4a19-97c0-6c2e0d157f5e.jpg",
      },
      {
        name: "emerald-lake",
        src: "src/client/assets/courses/fb608910-bafe-43d4-87a0-2a47e81356ef.jpg",
      },
      {
        name: "golden-meadow",
        src: "src/client/assets/courses/4c4e0c3b-bf85-4081-989b-8e3ea4a57bd5.jpg",
      },
      {
        name: "silent-harbor",
        src: "src/client/assets/courses/721cb2f0-5168-409a-b178-79728ed92e37.jpg",
      },
      {
        name: "misty-mountain",
        src: "src/client/assets/courses/156008b4-1855-4d09-ade4-07e4082eb333.jpg",
      },
      {
        name: "silver-river",
        src: "src/client/assets/courses/f86c62db-cfd6-4a02-b5b3-1d078fc4445c.jpg",
      },
      {
        name: "autumn-valley",
        src: "src/client/assets/courses/9b10ab1d-ea21-4d94-8af4-013ce21624cf.jpg",
      },
      {
        name: "frosty-peak",
        src: "src/client/assets/courses/6ecc0531-e6d0-453e-8fe7-750cd018f88a.jpg",
      },
      {
        name: "sunny-hills",
        src: "src/client/assets/courses/f95ab719-ed40-44c0-b248-2952c4118eee.jpg",
      },
      {
        name: "quiet-cove",
        src: "src/client/assets/courses/936ef989-53d2-4dfc-b7ce-7254ec2ff936.jpg",
      },
      {
        name: "hidden-grove",
        src: "src/client/assets/courses/e75380af-8b60-4c26-a676-8868f6645965.jpg",
      },
      {
        name: "willow-creek",
        src: "src/client/assets/courses/e75380af-8b60-4c26-a676-8868f6645965.jpg",
      },
      {
        name: "pine-ridge",
        src: "src/client/assets/courses/4a4118ab-b27d-44ae-90ba-b1e48be85f79.jpg",
      },
    ],
    userGroupImages: [
      {
        name: "crazy-groups",
        src: "src/client/assets/groups/6ddaf776-ebf9-4cae-91cd-1a1b95b89857.jpg",
      },
      {
        name: "azure-groups",
        src: "src/client/assets/groups/794e9a10-dd3b-4e75-97e9-dd8500fcc073.jpg",
      },
      {
        name: "groups-sunset",
        src: "src/client/assets/groups/0917a030-8ec5-44db-bc5f-623382437bec.jpg",
      },
      {
        name: "emerald-group",
        src: "src/client/assets/groups/c256245f-e63a-402b-81a3-688b57c28bda.jpg",
      },
    ],
    projectImages: [
      {
        name: "physical-topology",
        src: "src/client/assets/projects/1751433310.png",
        tags: "networking",
      },
      {
        name: "data-center",
        src: "src/client/assets/projects/4335662a-470a-42cc-af9b-7cd6b604b9de.jpg",
        tags: "networking",
      },
      {
        name: "data-center-2",
        src: "src/client/assets/projects/37bd2db6-bbd0-4524-93bc-ff5511f96f09.jpg",
        tags: "networking",
      },
      {
        name: "routers-and-switches",
        src: "src/client/assets/projects/8ba2115e-f708-4f8e-830e-9eb0d2da5332.jpg",
        tags: "networking",
      },
      {
        name: "routers-and-switches-2",
        src: "src/client/assets/projects/6c78003d-dbea-402d-99f2-9aac39e8ebb4.jpg",
        tags: "networking",
      },
      {
        name: "routers-and-switches-3",
        src: "src/client/assets/projects/7df2a902-d302-44ab-934d-abcd290ae2a1.jpg",
        tags: "networking",
      },
      {
        name: "hacking-guy",
        src: "src/client/assets/projects/dc31b93e-be9d-4d32-bafc-39fbb759cdf9.jpg",
        tags: "cybersecurity",
      },
      {
        name: "security-engineer",
        src: "src/client/assets/projects/b46c0a05-53a0-4a4a-932b-13502e5c96ef.jpg",
        tags: "cyberscurity",
      },
      {
        name: "malicious-attacker",
        src: "src/client/assets/projects/7e4efece-6b33-4fc8-a421-9c3bcfb79f25.jpg",
        tags: "cybersecurity",
      },
    ],
  } satisfies ImagesConfig,

  table: [
    {
      id: 1,
      header: "Cover page",
      type: "Cover page",
      status: "In Process",
      target: "18",
      limit: "5",
      reviewer: "Eddie Lake",
    },
    {
      id: 2,
      header: "Table of contents",
      type: "Table of contents",
      status: "Done",
      target: "29",
      limit: "24",
      reviewer: "Eddie Lake",
    },
    {
      id: 3,
      header: "Executive summary",
      type: "Narrative",
      status: "Done",
      target: "10",
      limit: "13",
      reviewer: "Eddie Lake",
    },
    {
      id: 4,
      header: "Technical approach",
      type: "Narrative",
      status: "Done",
      target: "27",
      limit: "23",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 5,
      header: "Design",
      type: "Narrative",
      status: "In Process",
      target: "2",
      limit: "16",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 6,
      header: "Capabilities",
      type: "Narrative",
      status: "In Process",
      target: "20",
      limit: "8",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 7,
      header: "Integration with existing systems",
      type: "Narrative",
      status: "In Process",
      target: "19",
      limit: "21",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 8,
      header: "Innovation and Advantages",
      type: "Narrative",
      status: "Done",
      target: "25",
      limit: "26",
      reviewer: "Assign reviewer",
    },
    {
      id: 9,
      header: "Overview of EMR's Innovative Solutions",
      type: "Technical content",
      status: "Done",
      target: "7",
      limit: "23",
      reviewer: "Assign reviewer",
    },
    {
      id: 10,
      header: "Advanced Algorithms and Machine Learning",
      type: "Narrative",
      status: "Done",
      target: "30",
      limit: "28",
      reviewer: "Assign reviewer",
    },
    {
      id: 11,
      header: "Adaptive Communication Protocols",
      type: "Narrative",
      status: "Done",
      target: "9",
      limit: "31",
      reviewer: "Assign reviewer",
    },
    {
      id: 12,
      header: "Advantages Over Current Technologies",
      type: "Narrative",
      status: "Done",
      target: "12",
      limit: "0",
      reviewer: "Assign reviewer",
    },
    {
      id: 13,
      header: "Past Performance",
      type: "Narrative",
      status: "Done",
      target: "22",
      limit: "33",
      reviewer: "Assign reviewer",
    },
    {
      id: 14,
      header: "Customer Feedback and Satisfaction Levels",
      type: "Narrative",
      status: "Done",
      target: "15",
      limit: "34",
      reviewer: "Assign reviewer",
    },
    {
      id: 15,
      header: "Implementation Challenges and Solutions",
      type: "Narrative",
      status: "Done",
      target: "3",
      limit: "35",
      reviewer: "Assign reviewer",
    },
    {
      id: 16,
      header: "Security Measures and Data Protection Policies",
      type: "Narrative",
      status: "In Process",
      target: "6",
      limit: "36",
      reviewer: "Assign reviewer",
    },
    {
      id: 17,
      header: "Scalability and Future Proofing",
      type: "Narrative",
      status: "Done",
      target: "4",
      limit: "37",
      reviewer: "Assign reviewer",
    },
    {
      id: 18,
      header: "Cost-Benefit Analysis",
      type: "Plain language",
      status: "Done",
      target: "14",
      limit: "38",
      reviewer: "Assign reviewer",
    },
    {
      id: 19,
      header: "User Training and Onboarding Experience",
      type: "Narrative",
      status: "Done",
      target: "17",
      limit: "39",
      reviewer: "Assign reviewer",
    },
    {
      id: 20,
      header: "Future Development Roadmap",
      type: "Narrative",
      status: "Done",
      target: "11",
      limit: "40",
      reviewer: "Assign reviewer",
    },
    {
      id: 21,
      header: "System Architecture Overview",
      type: "Technical content",
      status: "In Process",
      target: "24",
      limit: "18",
      reviewer: "Maya Johnson",
    },
    {
      id: 22,
      header: "Risk Management Plan",
      type: "Narrative",
      status: "Done",
      target: "15",
      limit: "22",
      reviewer: "Carlos Rodriguez",
    },
    {
      id: 23,
      header: "Compliance Documentation",
      type: "Legal",
      status: "In Process",
      target: "31",
      limit: "27",
      reviewer: "Sarah Chen",
    },
    {
      id: 24,
      header: "API Documentation",
      type: "Technical content",
      status: "Done",
      target: "8",
      limit: "12",
      reviewer: "Raj Patel",
    },
    {
      id: 25,
      header: "User Interface Mockups",
      type: "Visual",
      status: "In Process",
      target: "19",
      limit: "25",
      reviewer: "Leila Ahmadi",
    },
    {
      id: 26,
      header: "Database Schema",
      type: "Technical content",
      status: "Done",
      target: "22",
      limit: "20",
      reviewer: "Thomas Wilson",
    },
    {
      id: 27,
      header: "Testing Methodology",
      type: "Technical content",
      status: "In Process",
      target: "17",
      limit: "14",
      reviewer: "Assign reviewer",
    },
    {
      id: 28,
      header: "Deployment Strategy",
      type: "Narrative",
      status: "Done",
      target: "26",
      limit: "30",
      reviewer: "Eddie Lake",
    },
    {
      id: 29,
      header: "Budget Breakdown",
      type: "Financial",
      status: "In Process",
      target: "13",
      limit: "16",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 30,
      header: "Market Analysis",
      type: "Research",
      status: "Done",
      target: "29",
      limit: "32",
      reviewer: "Sophia Martinez",
    },
    {
      id: 31,
      header: "Competitor Comparison",
      type: "Research",
      status: "In Process",
      target: "21",
      limit: "19",
      reviewer: "Assign reviewer",
    },
    {
      id: 32,
      header: "Maintenance Plan",
      type: "Technical content",
      status: "Done",
      target: "16",
      limit: "23",
      reviewer: "Alex Thompson",
    },
    {
      id: 33,
      header: "User Personas",
      type: "Research",
      status: "In Process",
      target: "27",
      limit: "24",
      reviewer: "Nina Patel",
    },
    {
      id: 34,
      header: "Accessibility Compliance",
      type: "Legal",
      status: "Done",
      target: "18",
      limit: "21",
      reviewer: "Assign reviewer",
    },
    {
      id: 35,
      header: "Performance Metrics",
      type: "Technical content",
      status: "In Process",
      target: "23",
      limit: "26",
      reviewer: "David Kim",
    },
    {
      id: 36,
      header: "Disaster Recovery Plan",
      type: "Technical content",
      status: "Done",
      target: "14",
      limit: "17",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 37,
      header: "Third-party Integrations",
      type: "Technical content",
      status: "In Process",
      target: "25",
      limit: "28",
      reviewer: "Eddie Lake",
    },
    {
      id: 38,
      header: "User Feedback Summary",
      type: "Research",
      status: "Done",
      target: "20",
      limit: "15",
      reviewer: "Assign reviewer",
    },
    {
      id: 39,
      header: "Localization Strategy",
      type: "Narrative",
      status: "In Process",
      target: "12",
      limit: "19",
      reviewer: "Maria Garcia",
    },
    {
      id: 40,
      header: "Mobile Compatibility",
      type: "Technical content",
      status: "Done",
      target: "28",
      limit: "31",
      reviewer: "James Wilson",
    },
    {
      id: 41,
      header: "Data Migration Plan",
      type: "Technical content",
      status: "In Process",
      target: "19",
      limit: "22",
      reviewer: "Assign reviewer",
    },
    {
      id: 42,
      header: "Quality Assurance Protocols",
      type: "Technical content",
      status: "Done",
      target: "30",
      limit: "33",
      reviewer: "Priya Singh",
    },
    {
      id: 43,
      header: "Stakeholder Analysis",
      type: "Research",
      status: "In Process",
      target: "11",
      limit: "14",
      reviewer: "Eddie Lake",
    },
    {
      id: 44,
      header: "Environmental Impact Assessment",
      type: "Research",
      status: "Done",
      target: "24",
      limit: "27",
      reviewer: "Assign reviewer",
    },
    {
      id: 45,
      header: "Intellectual Property Rights",
      type: "Legal",
      status: "In Process",
      target: "17",
      limit: "20",
      reviewer: "Sarah Johnson",
    },
    {
      id: 46,
      header: "Customer Support Framework",
      type: "Narrative",
      status: "Done",
      target: "22",
      limit: "25",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 47,
      header: "Version Control Strategy",
      type: "Technical content",
      status: "In Process",
      target: "15",
      limit: "18",
      reviewer: "Assign reviewer",
    },
    {
      id: 48,
      header: "Continuous Integration Pipeline",
      type: "Technical content",
      status: "Done",
      target: "26",
      limit: "29",
      reviewer: "Michael Chen",
    },
    {
      id: 49,
      header: "Regulatory Compliance",
      type: "Legal",
      status: "In Process",
      target: "13",
      limit: "16",
      reviewer: "Assign reviewer",
    },
    {
      id: 50,
      header: "User Authentication System",
      type: "Technical content",
      status: "Done",
      target: "28",
      limit: "31",
      reviewer: "Eddie Lake",
    },
    {
      id: 51,
      header: "Data Analytics Framework",
      type: "Technical content",
      status: "In Process",
      target: "21",
      limit: "24",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 52,
      header: "Cloud Infrastructure",
      type: "Technical content",
      status: "Done",
      target: "16",
      limit: "19",
      reviewer: "Assign reviewer",
    },
    {
      id: 53,
      header: "Network Security Measures",
      type: "Technical content",
      status: "In Process",
      target: "29",
      limit: "32",
      reviewer: "Lisa Wong",
    },
    {
      id: 54,
      header: "Project Timeline",
      type: "Planning",
      status: "Done",
      target: "14",
      limit: "17",
      reviewer: "Eddie Lake",
    },
    {
      id: 55,
      header: "Resource Allocation",
      type: "Planning",
      status: "In Process",
      target: "27",
      limit: "30",
      reviewer: "Assign reviewer",
    },
    {
      id: 56,
      header: "Team Structure and Roles",
      type: "Planning",
      status: "Done",
      target: "20",
      limit: "23",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 57,
      header: "Communication Protocols",
      type: "Planning",
      status: "In Process",
      target: "15",
      limit: "18",
      reviewer: "Assign reviewer",
    },
    {
      id: 58,
      header: "Success Metrics",
      type: "Planning",
      status: "Done",
      target: "30",
      limit: "33",
      reviewer: "Eddie Lake",
    },
    {
      id: 59,
      header: "Internationalization Support",
      type: "Technical content",
      status: "In Process",
      target: "23",
      limit: "26",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 60,
      header: "Backup and Recovery Procedures",
      type: "Technical content",
      status: "Done",
      target: "18",
      limit: "21",
      reviewer: "Assign reviewer",
    },
    {
      id: 61,
      header: "Monitoring and Alerting System",
      type: "Technical content",
      status: "In Process",
      target: "25",
      limit: "28",
      reviewer: "Daniel Park",
    },
    {
      id: 62,
      header: "Code Review Guidelines",
      type: "Technical content",
      status: "Done",
      target: "12",
      limit: "15",
      reviewer: "Eddie Lake",
    },
    {
      id: 63,
      header: "Documentation Standards",
      type: "Technical content",
      status: "In Process",
      target: "27",
      limit: "30",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 64,
      header: "Release Management Process",
      type: "Planning",
      status: "Done",
      target: "22",
      limit: "25",
      reviewer: "Assign reviewer",
    },
    {
      id: 65,
      header: "Feature Prioritization Matrix",
      type: "Planning",
      status: "In Process",
      target: "19",
      limit: "22",
      reviewer: "Emma Davis",
    },
    {
      id: 66,
      header: "Technical Debt Assessment",
      type: "Technical content",
      status: "Done",
      target: "24",
      limit: "27",
      reviewer: "Eddie Lake",
    },
    {
      id: 67,
      header: "Capacity Planning",
      type: "Planning",
      status: "In Process",
      target: "21",
      limit: "24",
      reviewer: "Jamik Tashpulatov",
    },
    {
      id: 68,
      header: "Service Level Agreements",
      type: "Legal",
      status: "Done",
      target: "26",
      limit: "29",
      reviewer: "Assign reviewer",
    },
  ],
};
